### ISSUE TITLE
2.6.0 ブランチの作成

### ISSUE THREAD

**Issue by yono** [occ-corp/redmine#3]
## 作業項目
- [x] plugin の追加
- [x] 独自テーマの追加
- [x] Markdown の HTML エスケープを無効化

**Comment by yono** [comment]
@Tomohiro 今回の2.6アップデートでの作業項目を洗い出しました。

PR もこの項目に対応する形で出します。

**Comment by tomohiro** [comment]
:+1:  
よろしくおねがいします :bow:

**Comment by yono** [comment]
ソースへの変更は一通り終わったので、issue クローズします
